@baseUrl = http://localhost:8080/api/v1
@email = ownerone@doggydaycare.com
@password = ownerone123

###
# =======================
# Login
# =======================
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###
# =======================
# Example: Use token to access protected endpoint
# =======================
# Copy JWT from login-response "token"-field and put here:
@jwt = <PUT_YOUR_JWT_HERE>

GET {{baseUrl}}/users
Authorization: Bearer {{jwt}}
