@baseUrl = http://localhost:8080/api/v1
@userId = 4ce7b8ef-2b6f-4f73-848c-4ed2a1d0bb95
@dogId = 06806859-33e1-44fc-8f3c-a9172046f72f

###
# =======================
# Create dog
# =======================

POST {{baseUrl}}/dogs
Content-Type: application/json

{
  "name": "Flash",
  "age": 2,
  "breed": "Golden retriever",
  "dogInfo": "Jumps a lot, working on that with owner",
  "userId": "{{userId}}"
}

###
# =======================
# Read dog
# =======================

### Get dog by id
GET {{baseUrl}}/dogs/{{dogId}}

### Get all dogs
GET {{baseUrl}}/dogs

###
# =======================
# Update dog
# =======================

PUT {{baseUrl}}/dogs/{{dogId}}
Content-Type: application/json

{
  "age": 11,
  "breed": "Golden Retriever"
}

###
# =======================
# Delete dog (soft)
# =======================

DELETE {{baseUrl}}/dogs/{{dogId}}
