@baseUrl = http://localhost:8080/api/v1
@userId = e9a25cd1-c9d8-49fe-a442-0b714eee66dc

###
# =======================
# Create user
# =======================

POST {{baseUrl}}/users
Content-Type: application/json

{
  "email": "testinguser@doggydaycare.com",
  "password": "test123",
  "firstName": "Testing",
  "lastName": "User",
  "mobileNumber": "+46700000002",
  "emergencyContact": "+46700000007"
}

###
# =======================
# Read user
# =======================

### Get all users
GET {{baseUrl}}/users

### Get user by id
GET {{baseUrl}}/users/{{userId}}

### Get all dogs for a user
GET {{baseUrl}}/users/{{userId}}/dogs

###
# =======================
# Update user
# =======================

PUT {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "firstName": "Updated",
  "enabled": false
}

###
# =======================
# Delete user (soft)
# =======================

DELETE {{baseUrl}}/users/{{userId}}
